language: go

go:
  - 1.3

install:
  - go get -u -v code.google.com/p/go-uuid/uuid
  - go get -u -v github.com/fzzy/radix/redis
  - go get -u -v github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo
  - go get -u -v github.com/onsi/gomega
  - go get -u -v code.google.com/p/go.tools/cmd/cover
  - go get -u -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race
