language: go

go:
  - 1.3

install:
  - go get code.google.com/p/go-uuid/uuid
  - go get github.com/fzzy/radix/redis
  - go install github.com/onsi/ginkgo
  - go get github.com/onsi/gomega

script: ginkgo
